### ISSUE TITLE
The 'sync' endpoint is still not reliable

### ISSUE THREAD

**Issue by enckse** [epiphyte/matrix-bot#20]
because the `/sync/` endpoint doesn't understand how to operate I believe we're still being haunted by empty (no-JSON) responses

```
Aug 29 00:01:27 mbot bot.sh[31836]: Traceback (most recent call last):
Aug 29 00:01:27 mbot bot.sh[31836]:   File "<string>", line 88, in main
Aug 29 00:01:27 mbot bot.sh[31836]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Aug 29 00:01:27 mbot bot.sh[31836]:     return _default_decoder.decode(s)
Aug 29 00:01:27 mbot bot.sh[31836]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Aug 29 00:01:27 mbot bot.sh[31836]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Aug 29 00:01:27 mbot bot.sh[31836]:   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
Aug 29 00:01:27 mbot bot.sh[31836]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Aug 29 00:01:27 mbot bot.sh[31836]: json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by enckse** [comment]
still not reliable but not easy to fix
